from . import res_company
from . import res_config_settings
from . import stock_warehouse
from . import res_branch
from . import stock_location
from . import stock_picking_type
from . import stock_picking
from . import stock_move
from . import stock_move_line
from . import stock_quant
from . import stock_rule
